SUMMARY = "Replicape is a 3D printer cape for BeagleBone"
DESCRIPTION = "Software written in Python for maintainability and hackability."
HOMEPAGE = "http://wiki.replicape.com/index.php?title=Software"
SECTION = "devel"

LICENSE = "CC-BY-SA-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=d91509a59f42bb5341a8af8295f28211"

SRC_URI = "git://bitbucket.org/intelligentagent/replicape.git;protocol=https;branch=Rev-A4"
SRCREV = "4dc90dde5cd0eb49637cf244c7af6f4c57c0a0a4"

S = "${WORKDIR}/git"
